
site_name: Kennot の LeetCode 受難日記
site_url: https://phken91.github.io
theme:
  name: material
  palette:
    primary: teal
    scheme: slate
  language: zh-TW
  font: 
    text: Noto Sans Traditional Chinese
  features:
    - navigation.tracking
    - navigation.top
    - navigation.tracking
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables

plugins:
  - tags
  - blogging:
      locale: zh-TW
      time_format: '%Y-%m-%d %H:%M:%S'
      features:
        tags: {}
      dirs:
        - 部落格
      theme:
        name: card
# nav:
#   - 首頁:
#     - index.md
#   - 標籤:
#     - tags.md
extra:
  generator: false
  social:
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/hockkuan.phang